### ISSUE TITLE
Alpha fold dependencies plot protein command not executing

### ISSUE THREAD

**Issue by SatyajitMishra1** [google-deepmind/alphafold#1040]
<img width="1470" alt="Screenshot 2024-11-07 at 12 19 51 PM" src="https://github.com/user-attachments/assets/b81ded13-1a51-456d-bc89-ff1dc66d9841">

**Comment by Augustin-Zidek** [comment]
Hello, this looks like a ColabFold issue. Could you raise that in https://github.com/sokrypton/ColabFold?
