### ISSUE TITLE
Side chain Frame constrcution

### ISSUE THREAD

**Issue by wangleiofficial** [google-deepmind/alphafold#187]
For example:
```
# psi-frame to backbone
    mat = _make_rigid_transformation_4x4(
        ex=atom_positions['C'] - atom_positions['CA'],
        ey=atom_positions['CA'] - atom_positions['N'],
        translation=atom_positions['C'])
    restype_rigid_group_default_frame[restype, 3, :, :] = mat
```
From paper: `For the side chain frames, we use the atom before the torsion bond as x1, the atom after the torsion bond as x2 and the next atom after that as x3`.  but here, `CA` atom is the origin of the Psi frame,  can you help me to explain this code?

**Comment by YiyuHong** [comment]
@wangleiofficial Hi, Did you figure it out? I don't quite understand this part either.

**Comment by medic-code** [comment]
This piece of code creates a matrix that sets up transformation matrix and a translation point two orthogonal axis from C-CA and CA to N within the protein chain and an axis perpendicular to them both but also, setting to `C` atom position which is correct for a PSI frame.

So `For the side chain frames, we use the atom before the torsion bond as x1, the atom after the torsion bond as x2 and the next atom after that as x3` is correct but this piece of code does not relate to side chains.
