### ISSUE TITLE
mmCIF output

### ISSUE THREAD

**Issue by brindakv** [google-deepmind/alphafold#252]
Is there an option or a tool to generate output models and metadata in mmCIF format similar to the [files](https://alphafold.ebi.ac.uk/files/AF-Q8VCK6-F1-model_v1.cif) available from AlphafoldDB ?

**Comment by RodenLuo** [comment]
While waiting for the developers to respond with a new version, you can always use PyMol/ChimeraX to convert a PDB to mmCIF. Besides, you may find the below links useful. 

https://mmcif.pdbj.org/converter/index.php?l=en
https://sw-tools.rcsb.org/apps/SF-CONVERT/doc/V1-2-04/documentation.html

More broadly, 
https://sw-tools.rcsb.org/
https://mmtf.rcsb.org/
https://bioinformatics.stackexchange.com/questions/694/converter-between-pdb-or-mmcif-and-mmtf

**Comment by brindakv** [comment]
@RodenLuo Thank you. None these tools produce mmCIF files that include definitions in the [MA-dictionary](https://github.com/ihmwg/MA-dictionary), which the files from AlphafoldDB include.

**Comment by Augustin-Zidek** [comment]
Currently AlphaFold saves the output only in the PDB format, but we would like to add support ModelCIF-compliant mmCIF output. We will keep this issue open until it is added.

**Comment by russellp17** [comment]
Is it possible to release a script/snippet of code that can create an mmCIF file from the current output? That would be helpful even if it hasn't been integrated into the project yet

**Comment by j-kopec** [comment]
gemmi might be useful for such conversion https://gemmi.readthedocs.io/en/latest/utils.html?highlight=pdb%20to%20mmcif#convert

**Comment by russellp17** [comment]
Ah was mostly interested in formatting the files with quality data like they have in https://alphafold.ebi.ac.uk/ - don't see a way to do that with gemmi at first glance

**Comment by josemduarte** [comment]
I have a working implementation of ModelCIF writing (https://github.com/josemduarte/alphafold/commit/603d17277c858ede8b016163ced7bc0e9f50f16b). I'll consider to issue a PR once I can test it properly and iron out a few things.

So far all I've added is plddt local and global quality scores. Which for me is the main reason to use ModelCIF: tools like Mol* are ready to display plddt out-of-the-box.

Is there any other metadata features to write out that people would consider higher priority?

**Comment by huiwenke** [comment]
MineProt (https://github.com/huiwenke/MineProt) can be used to curate AlphaFold predictions, where PDBs are converted into CIFs using MAXIT (https://sw-tools.rcsb.org/apps/MAXIT/index.html). The generated CIF files support Mol* visualization and downstream analysis such as AlphaFill (https://github.com/PDB-REDO/alphafill).
Another possible option is to use MAXIT directly, while it needs several additional steps to make generated CIF files support older versions of Mol*. Please refer to https://github.com/huiwenke/MineProt/blob/master/web/api/pdb2alphacif/index.php.

**Comment by russellp17** [comment]
@josemduarte thank you! I ended up getting something working that operates on the current AlphaFold output using Biopython (parse the `ranked_0.pdb` file, use `ranking_debug.json` to figure out what model it corresponds to, parse the `result_model_x.pkl` file, ...) but it's probably much more straightforward to do within AlphaFold and it would be nice to have a canonical implementation.

The global pLDDT value is probably good to include, but looks like your code does that. I mostly tried to reverse-engineer the metadata in the https://alphafold.ebi.ac.uk/

**Comment by Augustin-Zidek** [comment]
We have added mmCIF output support to AlphaFold in https://github.com/deepmind/alphafold/commit/6c4d833fbd1c6b8e7c9a21dae5d4ada2ce777e10, mmCIF files are now generated alongside PDB files.

**Comment by brindakv** [comment]
Thanks @Augustin-Zidek.
