### ISSUE TITLE
Errors at the Search Against Genetic Database Cell - Colab

### ISSUE THREAD

**Issue by bsjcb** [google-deepmind/alphafold#363]
I keep getting the following error when I run the Search Against Genetic Database Cell:

<img width="1379" alt="Screenshot 2022-02-10 at 09 54 28" src="https://user-images.githubusercontent.com/99397024/153393846-338fc42a-4063-4422-960f-81b2fc29e412.png">

**Comment by joshabramson** [comment]
Hi @bsjcb - apologies that it has taken so long to reply to this issue. Do you still get an error with the latest version of AlphaFold?

**Comment by Augustin-Zidek** [comment]
Closing the issue as it is over a year old - feel free to open a new one if this is still a problem.
