### ISSUE TITLE
ValueError: Could not find Jackhmmer database /mnt/uniprot_database_path/uniprot.fasta

### ISSUE THREAD

**Issue by Pharmacy-student** [google-deepmind/alphafold#475]
Hi,
I am running an Alpha fold multimer , and i get the following error. I had try to running alphafold monomer , it worked. Anyone can give me a help?

"(alphafold) a507@507:/media/a507/GD/alphafold$ sudo python3 docker/run_docker.py \
>   --fasta_paths=6xnb.fasta \
>   --max_template_date=2022-05-14 \
>   --model_preset=multimer \
>   --data_dir=/media/a507/GD/alphafold_data
I0523 20:22:19.174425 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold -> /mnt/fasta_path_0
I0523 20:22:19.208586 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data/uniref90 -> /mnt/uniref90_database_path
I0523 20:22:19.244748 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data/mgnify -> /mnt/mgnify_database_path
I0523 20:22:19.260863 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data -> /mnt/data_dir
I0523 20:22:19.325441 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0523 20:22:19.347388 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0523 20:22:19.403382 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data/uniprot -> /mnt/uniprot_database_path
I0523 20:22:19.434726 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data/pdb_seqres -> /mnt/pdb_seqres_database_path
I0523 20:22:19.474366 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0523 20:22:19.505920 140380645635904 run_docker.py:113] Mounting /media/a507/GD/alphafold_data/bfd -> /mnt/bfd_database_path
I0523 20:22:31.748290 140380645635904 run_docker.py:255] I0523 12:22:31.747724 140410703603520 templates.py:857] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0523 20:22:31.889975 140380645635904 run_docker.py:255] E0523 12:22:31.889359 140410703603520 jackhmmer.py:75] Could not find Jackhmmer database /mnt/uniprot_database_path/uniprot.fasta
I0523 20:22:31.890795 140380645635904 run_docker.py:255] Traceback (most recent call last):
I0523 20:22:31.890882 140380645635904 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 422, in <module>
I0523 20:22:31.890947 140380645635904 run_docker.py:255] app.run(main)
I0523 20:22:31.891010 140380645635904 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0523 20:22:31.891072 140380645635904 run_docker.py:255] _run_main(main, args)
I0523 20:22:31.891132 140380645635904 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0523 20:22:31.891192 140380645635904 run_docker.py:255] sys.exit(main(argv))
I0523 20:22:31.891252 140380645635904 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 357, in main
I0523 20:22:31.891322 140380645635904 run_docker.py:255] use_precomputed_msas=FLAGS.use_precomputed_msas)
I0523 20:22:31.891383 140380645635904 run_docker.py:255] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 193, in __init__
I0523 20:22:31.891441 140380645635904 run_docker.py:255] database_path=uniprot_database_path)
I0523 20:22:31.891508 140380645635904 run_docker.py:255] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 76, in __init__
I0523 20:22:31.891589 140380645635904 run_docker.py:255] raise ValueError(f'Could not find Jackhmmer database {database_path}')
I0523 20:22:31.891651 140380645635904 run_docker.py:255] ValueError: Could not find Jackhmmer database /mnt/uniprot_database_path/uniprot.fasta "

**Comment by tcoates5** [comment]
When I had similar problems, it was because I had not properly downloaded/unpacked uniprot.fasta. I remember that the reason it happened is that with how slowly some of the downloads were going I mistakenly thought it finished when it had not

**Comment by BurcuOzden** [comment]
We have the same error. Could you solve the problem by downloading it again?

**Comment by Pharmacy-student** [comment]
> We have the same error. Could you solve the problem by downloading it again?

Hi, I  have solved this problem. I've tried redownloading, but it didn't work. Later I renamed "uniprot_trembl.fasta" in the "uniprot" folder to "uniprot.fasta" and I was able to use the multimerfold. I don't know if I'm doing this right, but at least it works

**Comment by BurcuOzden** [comment]
Thank you for your recommendation. I will try to redownload it and if it doesn't work, I will apply this.

**Comment by morin-andrew** [comment]
The renaming solution offered by "[Pharmacy-student Kevin" above worked for me.

**Comment by thekingofall** [comment]
The renaming solution offered by "[Pharmacy-student Kevin" above  also worked for me.

**Comment by yamule** [comment]
'uniprot.fasta' is generated from 2 files. 'uniprot_trembl.fasta(.gz)' and 'uniprot_sprot.fasta(.gz)'.
'uniprot_trembl.fasta(.gz)' is a bit big that it may take some hours.
If you don't find 'uniprot_sprot.fasta(.gz)', it might mean download process is incomplete.
(Let's see https://github.com/deepmind/alphafold/blob/main/scripts/download_uniprot.sh .)

The server defined in the script is sometimes slow from some locations, so changing it to an appropriate mirror will give you a better result, I guess. https://www.uniprot.org/release-notes/downloads
I'm in Japan and using the Switzerland server.

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）

**Comment by DantongWang** [comment]
> 'uniprot.fasta' is generated from 2 files. 'uniprot_trembl.fasta(.gz)' and 'uniprot_sprot.fasta(.gz)'. 'uniprot_trembl.fasta(.gz)' is a bit big that it may take some hours. If you don't find 'uniprot_sprot.fasta(.gz)', it might mean download process is incomplete. (Let's see https://github.com/deepmind/alphafold/blob/main/scripts/download_uniprot.sh .)
> 
> The download from the server defined in the script is sometimes slow from some locations, so changing it to an appropriate mirror will give you a better result, I guess. https://www.uniprot.org/release-notes/downloads I'm in Japan and using the Switzerland server.

Hi yamule, shall I ask how is 'uniprot.fasta' generated from the 2 files? Simply copy them together? I currently have them both, so want to know if there is a way to get 'uniprot.fasta' faster than re-download the whole database. ;)

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）

**Comment by yamule** [comment]
> > 'uniprot.fasta' is generated from 2 files. 'uniprot_trembl.fasta(.gz)' and 'uniprot_sprot.fasta(.gz)'. 'uniprot_trembl.fasta(.gz)' is a bit big that it may take some hours. If you don't find 'uniprot_sprot.fasta(.gz)', it might mean download process is incomplete. (Let's see https://github.com/deepmind/alphafold/blob/main/scripts/download_uniprot.sh .)
> > The download from the server defined in the script is sometimes slow from some locations, so changing it to an appropriate mirror will give you a better result, I guess. https://www.uniprot.org/release-notes/downloads I'm in Japan and using the Switzerland server.
> 
> Hi yamule, shall I ask how is 'uniprot.fasta' generated from the 2 files? Simply copy them together? I currently have them both, so want to know if there is a way to get 'uniprot.fasta' faster than re-download the whole database. ;)

A bit late so you may have already solved the problem,

As far as I understand,
These lines
https://github.com/google-deepmind/alphafold/blob/f715f016d875e2fd8515457af2b12277a716b9b0/scripts/download_uniprot.sh#L52C1-L53C73
indicate just the contents of uniprot_sprot.fasta are concatenated after the contents of uniprot_trembl.fasta .
And the filename is changed to uniprot.fasta .

Thus if you have two files, uniprot_trembl.fasta and uniprot_sprot.fasta,
`cat uniprot_trembl.fasta uniprot_sprot.fasta > uniprot.fasta`
will work.
if they are gzipped, 
`zcat uniprot_trembl.fasta.gz uniprot_sprot.fasta.gz > uniprot.fasta`
will work.
(The download_uniprot.sh overwrites uniprot_trembl.fasta but I made a new file in case we have unexpected accident. It consumes larger disk space, tho.)

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）

**Comment by changhao111** [comment]
The renaming solution offered by "[Pharmacy-student Kevin" above worked for me.

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）
