### ISSUE TITLE
2.3.2: update version number in setup.py

### ISSUE THREAD

**Issue by lucajovine** [google-deepmind/alphafold#744]
Hi, setup.py of 2.3.2 still lists the version as 2.3.1, you may want to update it.

**Comment by Augustin-Zidek** [comment]
Thanks. Fixed properly in https://github.com/google-deepmind/alphafold/commit/6c4d833fbd1c6b8e7c9a21dae5d4ada2ce777e10 (there is now a single source of truth for AlphaFold version).
