### ISSUE TITLE
Which file should I use from Alphafold output? 

### ISSUE THREAD

**Issue by AlexisGGk** [google-deepmind/alphafold#829]
Hi, 

So, I have generated a lot of structures using Alphafold on a computing cluster. Each protein prediction generates 17 predicted structures. Only one of them is specifically marked as being a relaxed structure, and it is my understanding that the relaxed structures are better to use. 

Each folder has a different numbered model generated (in the example shown, it is 4). I wondered why it only relaxes one structure and whether it is reasonable only to use the relaxed structures for further work, irrespective of what number is assigned to them. 

<img width="668" alt="Screenshot 2023-09-05 at 11 19 01" src="https://github.com/deepmind/alphafold/assets/131365849/e69c8336-c530-45f7-9928-1e4dcd02757f">

**Comment by tcoates5** [comment]
This output actually raises some questions for me. Simply put, it looks as if you are missing several outputs. My outputs always include one relaxed for every unrelaxed and one ranked for every relaxed. By default, using the multimer run this gives me a total of 75 output structures (25 unrelaxed, 25 relaxed, 25 ranked), and monomer gave me 15 (same pattern). Each relaxed is the output from an MD minimization of an unrelaxed and each ranked is a renamed copy of a relaxed. I also see 11 structures and 6 pickles in your outputs, as opposed to 17 structure files, though it looks like you have a program set up to read the pickles as structures? Or at least the same default program to open both.

**Comment by Htomlinson14** [comment]
Hi -- what models are relaxed can be controlled in the script: https://github.com/deepmind/alphafold/blob/main/run_alphafold.py#L132.

By default it only relaxes the best (highest confidence) model, but it can be set to relaxing all (but this will take longer).

**Comment by AlexisGGk** [comment]
Okay, so @Htomlinson14, it would seem then that it is only outputting the highest confidence model (which is all I need). So presumably @tcoates5, all that is happening is that the person who set up alphafold on the HPC cluster has made it a little more streamlined hence fewer outputs since it seems optimised for a single high-accuracy structure?
