### ISSUE TITLE
download_pdb_seqres.sh uses HTTP, only works for FTP

### ISSUE THREAD

**Issue by GaryAitken** [google-deepmind/alphafold#835]
The script download_pdb_seqres.sh uses the URL
```
https://ftp.wwpdb.org/pub/pdb/derived_data/pdb_seqres.txt
```
That url doesn't work; the file must be downloaded using anonymous ftp.

**Comment by dcroote** [comment]
#838 solved this for me

**Comment by Augustin-Zidek** [comment]
Thanks for reporting, fixed in https://github.com/google-deepmind/alphafold/commit/f78c5893044aa148be7f020f8a1094a556893184.
