### ISSUE TITLE
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

### ISSUE THREAD

**Issue by duetduet** [google-deepmind/alphafold#836]
I am running a multimer prediction online using the ColabFold v1.5.2-patch: AlphaFold2 using MMseqs2. I believe this is the most recent version.

I have selected "1" for num_relax field as I would like amber relaxation performed on the top ranked model. However, every time I make this selection, it gets through making all the models but then failing to progress after that. Here are the final lines in the "Run prediction" cell:

2023-10-03 04:09:49,462 reranking models by 'multimer' metric
2023-10-03 04:09:52,637 Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
 
My run appears stalled and seems to not progress further. I ran the same sequences without any amber relaxation (num_relax = 0) and I did not get this error message and the run was successfully completed with an output file with albiet unrelaxed models. I require the relaxed models. How can I overcome this error message?

Cheers!

**Comment by sokrypton** [comment]
Could you post the example you used?

**Comment by duetduet** [comment]
The run was eventually completed.

**Comment by duetduet** [comment]
> The run was eventually completed.
