### ISSUE TITLE
failing to download obsolete.dat

### ISSUE THREAD

**Issue by m3hdad** [google-deepmind/alphafold#837]
Failing to download `obsolete.dat` in `download_pdb_mmcif.sh`, changing `https://` to `ftp://`:

```
aria2c "https://ftp.wwpdb.org/pub/pdb/data/status/obsolete.dat" --dir="${ROOT_DIR}"
```

to

```
aria2c "ftp://ftp.wwpdb.org/pub/pdb/data/status/obsolete.dat" --dir="${ROOT_DIR}"
```

https://github.com/google-deepmind/alphafold/blob/7c9114c8423ac9db981d8365168464bab09b3e54/scripts/download_pdb_mmcif.sh#L65C17-L65C20

**Comment by dcroote** [comment]
#838 solved this for me

**Comment by Augustin-Zidek** [comment]
Thanks for reporting, fixed in https://github.com/google-deepmind/alphafold/commit/f78c5893044aa148be7f020f8a1094a556893184.
