### ISSUE TITLE
Unstable iptm+ptm

### ISSUE THREAD

**Issue by cfz1998** [google-deepmind/alphafold#839]
Hi! @tomhennigan 

https://github.com/HommaF/AlphaFold2_chapter/issues/1

**Comment by FelixHomma** [comment]
> Hi! @tomhennigan 
> 
> https://github.com/HommaF/AlphaFold2_chapter/issues/1

Just responded in the linked repo where you raised the question originally.

**Comment by cfz1998** [comment]
Thank you very much! @FelixHomma 
After removing the prodomain of the protease, I got stable iptm+ptm values.

    "iptm+ptm": {
        "model_1_multimer_v3_pred_0": 0.9130940645044535,
        "model_2_multimer_v3_pred_0": 0.9080438523780853,
        "model_3_multimer_v3_pred_0": 0.9171108252434494,
        "model_4_multimer_v3_pred_0": 0.9183709633181361,
        "model_5_multimer_v3_pred_0": 0.9209148930632896
