### ISSUE TITLE
I am trying to install alphafold without docker version and after successful installation and activation of the environment, I am still getting the following error. 

### ISSUE THREAD

**Issue by BIPASAkar** [google-deepmind/alphafold#844]
Installing collected packages: alphafold
Successfully installed alphafold-2.0.0
(alphafold-venv) bik68jw@wbbi206:~/alphafold$ ls
afdb       CONTRIBUTING.md  docs  LICENSE    README.md         run_alphafold.py       scripts
alphafold  docker           imgs  notebooks  requirements.txt  run_alphafold_test.py  setup.py
(alphafold-venv) bik68jw@wbbi206:~/alphafold$ alphafold --version
-bash: alphafold: command not found  

Please give me some suggestions. 

Thank you in advance

**Comment by ebettler** [comment]
Try following this protocole: https://github.com/kalininalab/alphafold_non_docker
