### ISSUE TITLE
module 'jax' has no attribute 'xla'

### ISSUE THREAD

**Issue by singh1900** [google-deepmind/alphafold#852]
I am getting this error (module 'jax' has no attribute 'xla') while running the alphafold. Can anyone suggest the solution.
![alphafold problem](https://github.com/google-deepmind/alphafold/assets/150079871/aa7cff04-0b9a-445e-bd44-d0da32225787)
`AttributeError                            Traceback (most recent call last)
[<ipython-input-13-4ac7c8f9d819>](https://localhost:8080/#) in <cell line: 55>()
     58     runner = cf_af.prep_model_runner(opt, old_runner=runner)
     59   else:
---> 60     runner = cf_af.prep_model_runner(opt)
     61 else:
     62   runner = None

7 frames
[/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py](https://localhost:8080/#) in getattr(name)
     51       warnings.warn(message, DeprecationWarning, stacklevel=2)
     52       return fn
---> 53     raise AttributeError(f"module {module!r} has no attribute {name!r}")
     54 
     55   return getattr

AttributeError: module 'jax' has no attribute 'xla'`

**Comment by Htomlinson14** [comment]
Ho this is a colabfold notebook. Please raise the issue there. Thanks!
