### ISSUE TITLE
Error On Section 4, Symbol Zeros is already exposed as ()

### ISSUE THREAD

**Issue by wilEd22** [google-deepmind/alphafold#876]
Im getting this error message when trying to run AlphaFold colab, any suggestions? 

<img width="1295" alt="image" src="https://github.com/google-deepmind/alphafold/assets/154385968/980764f4-b86e-4578-ac70-2d6f8d21fae6">

**Comment by Zhang038** [comment]
The same issue happens to me as well.

**Comment by XiangtaiKong** [comment]
So do I.

**Comment by Fspartade** [comment]
hhh,metoo

**Comment by SK1-biocopy** [comment]
I encounter the same issue. I guess this is the same bug as #875

**Comment by Htomlinson14** [comment]
Thanks to @omikhailovskii for suggesting uninstalling keras. Colab should now be working after https://github.com/google-deepmind/alphafold/commit/632ef575c64eff9eb5ed96c8c7b055bf675421ac
