### ISSUE TITLE
Notebook - Cell 4 "Making Prediction" - SymbolAlreadyExposedError

### ISSUE THREAD

**Issue by Sabi89129** [google-deepmind/alphafold#878]
Hi !
I have run the first 3 cells in the google [colab notebook](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb) without any issues. However in the fourth cell (4. Search against genetic databases) I got this error. Any ideas what went wrong? I did not change any code.

**SymbolAlreadyExposedError                 Traceback (most recent call last)
[<ipython-input-19-f1fdee26350e>](https://localhost:8080/#) in <cell line: 27>()
     25 import py3Dmol
     26 
---> 27 from alphafold.model import model
     28 from alphafold.model import config
     29 from alphafold.model import data

22 frames
[/opt/conda/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py](https://localhost:8080/#) in set_attr(self, func, api_names_attr, names)
    362     if api_names_attr in func.__dict__:
    363       if not self._allow_multiple_exports:
--> 364         raise SymbolAlreadyExposedError(**
    365             'Symbol %s is already exposed as %s.' %
    366             (func.__name__, getattr(func, api_names_attr)))  # pylint: disable=protected-access

SymbolAlreadyExposedError: Symbol Zeros is already exposed as ().

**Comment by MerlockMoe** [comment]
im getting the same error. Normally i would clean everything related to alphafold and then reinstall it. i tried that, but it produced the same error afterwards.
Could u fix it?

**Comment by sealook** [comment]
Getting the same error.

**Comment by jfbazan** [comment]
Same error, now on Jan 25, a month after originally logged.... :[. 

Dear DeepMind AF folks, could you pls fix this rather outstanding bug? This is your Colab, and I suspect that it should be widely used, so why the delay and lack of response? Thx in advance for your consideration and diligence.

Here's the error msg:

---------------------------------------------------------------------------
SymbolAlreadyExposedError                 Traceback (most recent call last)
[<ipython-input-4-f1fdee26350e>](https://li6qmfaj54m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240124-060116_RC01_601156319#) in <cell line: 27>()
     25 import py3Dmol
     26 
---> 27 from alphafold.model import model
     28 from alphafold.model import config
     29 from alphafold.model import data

22 frames
[/opt/conda/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py](https://li6qmfaj54m-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240124-060116_RC01_601156319#) in set_attr(self, func, api_names_attr, names)
    362     if api_names_attr in func.__dict__:
    363       if not self._allow_multiple_exports:
--> 364         raise SymbolAlreadyExposedError(
    365             'Symbol %s is already exposed as %s.' %
    366             (func.__name__, getattr(func, api_names_attr)))  # pylint: disable=protected-access

SymbolAlreadyExposedError: Symbol Zeros is already exposed as ().

**Comment by Htomlinson14** [comment]
Thanks to @omikhailovskii for suggesting uninstalling keras. Colab should now be working after https://github.com/google-deepmind/alphafold/commit/632ef575c64eff9eb5ed96c8c7b055bf675421ac
