### ISSUE TITLE
Downloading mmCIF files problem

### ISSUE THREAD

**Issue by mavino** [google-deepmind/alphafold#901]
Hi there,
I have a problem when trying to download mmCIF files, can you help me? Thank you very much.
```
bash download_pdb_mmcif.sh $SCRATCH/alphafold/data
Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)...
If the download speed is too slow, try changing the mirror to:
  * rsync.ebi.ac.uk::pub/databases/pdb/data/structures/divided/mmCIF/ (Europe)
  * ftp.pdbj.org::ftp_data/structures/divided/mmCIF/ (Asia)
or see https://www.wwpdb.org/ftp/pdb-ftp-sites for more download options.
 69,912,384,302 100%    7.68MB/s    2:24:36 (xfr#216225, to-chk=0/217286)   
Unzipping all mmCIF files...
gzip: /scratch/avim2701/alphafold/data/pdb_mmcif/raw/t0/7t0s.cif.gz: Input/output error
gzip: /scratch/avim2701/alphafold/data/pdb_mmcif/raw/t0/5t08.cif.gz: Input/output error
```

**Comment by tejhande** [comment]
Disk Space: Check if there's enough space available in the directory where you're downloading the files.
Retry Download: Sometimes, network issues can cause transient errors. Try downloading the files again.
File Permissions: Ensure you have the necessary permissions to write to the directory.
File Integrity: Download a few files manually to see if the error persists. It might be specific to certain files.
Contact Data Provider: If the problem persists, reach out to the data provider for assistance.
Disk Health: Consider running diagnostics on your disk to check for any potential issues."

**Comment by mavino** [comment]
I do not remember how I solved this issue...maybe the problem was that I was connected to a login node or one that @tejhande listed.
