### ISSUE TITLE
Getting more than 25 predicted models for multimer mode

### ISSUE THREAD

**Issue by varunmc92** [google-deepmind/alphafold#907]
I am currently working with an antibody with known epitope and paratope. I used AF2-multimer to make poses of the antigen-antibody complex but none of the 25 poses had the correct epitope residues. Is there any way I can increase the number of final poses made from the default 25 to 50 or 500 to increase the odds of finding a pose that has the correct interface residues? Thanks

**Comment by Htomlinson14** [comment]
Hi -- yes in the docker runner you can choose num_multimer_predictions_per_model. There are 5 models, so this will generate 5 times this number (currently default to 5, hence 25).

**Comment by varunmc92** [comment]
Thanks for the quick reply. I was under the impression that the poses made by a model will be similar and increasing the seeds will not lead to drastic changes in poses made by that model.

**Comment by tcoates5** [comment]
> Thanks for the quick reply. I was under the impression that the poses made by a model will be similar and increasing the seeds will not lead to drastic changes in poses made by that model.

That is usually, though not always, accurate. To increase the diversity of what you sample you can also reduce the level of recycling used, or tinker with the MSA parameters (for example, making the max-identity parameter stricter). Combining this with other parameters that increase the number of outputs may very well help you find what you are looking for.

**Comment by varunmc92** [comment]
Thanks for the reply. Currently my company has downloaded the latest version of AF2 onto our local systems. Could you kindly guide me to the files where I can manipulate these recycle and MSA parameters? I can see that I can make these changes in CollabFold but not sure where to do it in AlphaFold. Thanks
