### ISSUE TITLE
Downloaded cif file from open access doesn't have secondary structure assignments

### ISSUE THREAD

**Issue by jiangandrew** [google-deepmind/alphafold#936]
Model 0 (fold_2024_05_13_11_18_model_0.cif) appears to be a protein without secondary structure assignments." 
KeyError: 'pdbx_description'  
File '/Applications/Chimera.app/Contents/Resources/share/chimera/Sequence.py", line 993 in getSequences description = entity[index]['pdbx_description']

**Comment by e-pettersen** [comment]
This was fixed in Chimera at the end of last week.  You have to use a daily build to get the fix.

**Comment by jiangandrew** [comment]
It works with the newest daily build. Thank you so much for your help!

**Comment by jiangandrew** [comment]
It works with the newest daily build. Thank you so much for your help!
